spring:  
  datasource:
    username: call_log
    password: call_log
    url: jdbc:mysql://localhost:3306/call_log
    
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
#    defer-datasource-initialization: true
    
#  sql: 
#    init:
#      mode: never
      